export interface  SellerSales {
    id: number,
      total_price: number,
      total_quantity:number,
      total_taxes:number,
      total: number,
      note: string,
      extra_discount: number,
      order_number: number,
      returns: number,
      latitude: string,
      longitude: string,
      client_count:number,
      orders_count: number,
      orders_sum: number,
      related_clients_count: number,
      nonrelated_clients_count: number,
      percentage_sales: number,
      percentage_company_sales: number,
      client_sales_percentage: number,
      all_clients_count: number,
      target: number,
      percentage_target:number,
      salesman_name: number,
      created_at: string,
      order_status: 0,
      total_after_extra_discount: number,
      pharmacy_name: number,
      status: string,
      shipping_type: string
}